const data = [
    [
        "Ayodhya Dham Bus Station",
        "Saket Over Bridge",
        "Lata Chowk",
        "Duragagunj",
        "Katra",
        "Duragagunj",
        "Lata Chowk",
        "Sringar hot",
        "Hanuman Gadi",
        "Shriram Hospital",
        "Tedi Bazar",
        "Uday Chauraha",
        "Amanigunj",
        "Chowk ",
        "Niyaba",
        "Rikabgunj",
        "Ayodhya bus Station",
        "Kacheri",
        "Sahadatgunj",
    ],
    [
        "Salarpur",
        "Purekashi",
        "Raipur",
        "Mumtaj Nagar",
        "Politechnic ",
        "Sahadatgunj",
        "Kacheri",
        "Ayodhya bus Station",
        "Rikabgunj",
        "Niyaba",
        "Gudadi bazar",
        "Sahabganj",
        "Amanigunj",
        "Uday Chauraha",
        "Tedi Bazar",
        "Shriram Hospital",
        "Hanuman Gadi",
        "Sringar hot",
        "Lata Chowk",
        "Saket Over Bridge",
        "Ayodhya Dham Bus Station",
    ],
    [
        "Ayodhya Dham Bus Station",
        "4 no.Booth",
        "Mehabara",
        "Devkali",
        "Bhikapur",
        "Janura",
        "Naka",
        "Fatehganj",
        "Police Line",
        "Cant Railway Station",
        "Ayodhya bus Station",
        "Kachehri",
        "Sahadatganj hanuman gadi",
        "Sahadatganj",
        "RTO Office",
        "Raibarelly Mod",
        "Naka Sultanpur",
        "Chandpur",
        "Damasemar",
        "Krishi Vigyan",
        "Masudha",
        "Purakalendar",
        "Tv Hospital",
        "Workshop",
        "Bharatkund",
    ],
    [
        "Ayodhya Dham Bus Station",
        "4 no.Booth",
        "Mehabara",
        "Devkali",
        "Bhikapur",
        "Janura",
        "Naka",
        "Fatehganj",
        "Police Line",
        "Cant Railway Station",
        "Ayodhya bus Station",
        "Kachehri",
        "Sahadatganj hanuman gadi",
        "Sahadatganj",
        "RTO Office",
        "Raibarelly Mod",
        "Pegapur",
        "Maushiwala",
        "Prabhat Nagar",
        "Sariyavan",
        "Ranibazar",
        "Amouna",
        "Nauvya Kuan",
        "Barun Bazar",
    ],
    [
        "Ayodhya Dham Bus Station",
        "4 no.Booth",
        "Surajkund",
        "Parakhan",
        "S Paper Mill ",
        "Sarairasi",
        "Rajepur",
        "Pura Bazar",
        "Rajepur",
        "Sarairasi",
        "S Paper Mill ",
        "Parakhan",
        "Surajkund",
        "4 no.Booth",
        "Mehabara",
        "Devkali",
        "Bhikapur",
        "Naka",
        "Raibarelly Mod",
        "RTO Office",
        "Sahadatganj",
        "Kachehri",
        "Ayodhya bus Station",
        "Cant Railway Station",
    ],
];

export default data;